services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      timeout: 10s
    ports:
      - 3306:3306
    networks:
      - my_net
    volumes:
      - mysql_db:/var/lib/mysql
  flask_app:
    build: 
      context: .
      dockerfile: Dockerfile.multistage
    container_name: flask_app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
    ports:
      - 5000:5000
    networks:
      - my_net
networks:
  my_net:
volumes:
  mysql_db:
