name: Secret Test

on:
    push:
        branches: [main]

jobs:
    check-secret:
        runs-on: ubuntu-latest
        steps:
            - name: Check if secret exist
              run: |
                if [ -z "${{ secrets.MY_SECRET_MESSAGE }}" ];then
                    echo "Secret is set: false"
                else
                    echo "Secret is set: true"
                fi
                