name: Secret Credentials

on:
    push:
        branches: [main]

jobs:
    use-secret-env:
        runs-on: ubuntu-latest
        steps:
            - name: Use secret as environment variable
              env:
                MY_SECRET_MESSAGE: ${{ secrets.MY_SECRET_MESSAGE }}
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
              run: |
                echo "Secret message: ${MY_SECRET_MESSAGE}"
                echo "DOCKER_USERNAME: ${DOCKER_USERNAME}"
                echo "DOCKER_PASSWORD: ${DOCKER_PASSWORD}"